apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: threescale-productized-operators-latest-catalog
  namespace: rhi-apimgmt
spec:
  sourceType: grpc
  image: quay.io:443/3scale/rh-3scale-operator-index:3scale2.12.dev
  publisher: "3scale Engineering Continuous Productization"
