apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: qe-tests-apimanager
spec:
  wildcardDomain: insert_your_wildcard_domain_here

#  should be default now, due to new OperatorSource
#  apicast:
#    image: "quay.io/3scale/rh-apicast:3scale2.9"
#  backend:
#    image: "quay.io/3scale/rh-apisonator:3scale2.9"
#  system:
#    image: "quay.io/3scale/rh-porta:3scale2.9"
#  zync:
#    image: "quay.io/3scale/rh-zync:3scale2.9"

# comment out below line to deploy full 3scale version
  resourceRequirementsEnabled: false

# This assumes that nfs-provisioner is deployed on the cluster. comment out to use default provider for RWX PVC
  system:
    fileStorage:
      persistentVolumeClaim:
        storageClassName: nfs
