apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: apimanager-role
  namespace: target # Should be namespace you are granting access to
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
